spring.application.name=ServicioAnotaciones

spring.web.error.include-binding-errors=always
spring.web.error.include-message=always

spring.datasource.url=jdbc:mysql://localhost:3306/fs_servicioanotaciones?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=system
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

server.port=5006

services.usuario.url=http://127.0.0.1:5000/registro
services.vidaestudiantil.url=http://127.0.0.1:5002/hojas-vida
services.mensajeria.url=http://127.0.0.1:5004/mensajeria

#Swagger config
springdoc.swagger-ui.path=/servicioAnotaciones.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operations-sorter=alpha